//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://energycode.pnl.gov/ns/ComCheckBuildingSchema")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://energycode.pnl.gov/ns/ComCheckBuildingSchema", IsNullable=false)]
public partial class building {
    
    private string projectTypeField;
    
    private string bldgUseTypeField;
    
    private decimal feetBldgHeightField;
    
    private bool isNonresidentialConditioningField;
    
    private bool isResidentialConditioningField;
    
    private bool isSemiheatedConditioningField;
    
    private string conditioningField;
    
    private buildingControl controlField;
    
    private buildingLocation locationField;
    
    private buildingProject projectField;
    
    private buildingEnvelope envelopeField;
    
    private buildingLighting lightingField;
    
    private buildingHvac hvacField;
    
    private buildingRequirementAnswer[] requirementsField;
    
    /// <remarks/>
    public string projectType {
        get {
            return this.projectTypeField;
        }
        set {
            this.projectTypeField = value;
        }
    }
    
    /// <remarks/>
    public string bldgUseType {
        get {
            return this.bldgUseTypeField;
        }
        set {
            this.bldgUseTypeField = value;
        }
    }
    
    /// <remarks/>
    public decimal feetBldgHeight {
        get {
            return this.feetBldgHeightField;
        }
        set {
            this.feetBldgHeightField = value;
        }
    }
    
    /// <remarks/>
    public bool isNonresidentialConditioning {
        get {
            return this.isNonresidentialConditioningField;
        }
        set {
            this.isNonresidentialConditioningField = value;
        }
    }
    
    /// <remarks/>
    public bool isResidentialConditioning {
        get {
            return this.isResidentialConditioningField;
        }
        set {
            this.isResidentialConditioningField = value;
        }
    }
    
    /// <remarks/>
    public bool isSemiheatedConditioning {
        get {
            return this.isSemiheatedConditioningField;
        }
        set {
            this.isSemiheatedConditioningField = value;
        }
    }
    
    /// <remarks/>
    public string conditioning {
        get {
            return this.conditioningField;
        }
        set {
            this.conditioningField = value;
        }
    }
    
    /// <remarks/>
    public buildingControl control {
        get {
            return this.controlField;
        }
        set {
            this.controlField = value;
        }
    }
    
    /// <remarks/>
    public buildingLocation location {
        get {
            return this.locationField;
        }
        set {
            this.locationField = value;
        }
    }
    
    /// <remarks/>
    public buildingProject project {
        get {
            return this.projectField;
        }
        set {
            this.projectField = value;
        }
    }
    
    /// <remarks/>
    public buildingEnvelope envelope {
        get {
            return this.envelopeField;
        }
        set {
            this.envelopeField = value;
        }
    }
    
    /// <remarks/>
    public buildingLighting lighting {
        get {
            return this.lightingField;
        }
        set {
            this.lightingField = value;
        }
    }
    
    /// <remarks/>
    public buildingHvac hvac {
        get {
            return this.hvacField;
        }
        set {
            this.hvacField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("requirementAnswer", IsNullable=false)]
    public buildingRequirementAnswer[] requirements {
        get {
            return this.requirementsField;
        }
        set {
            this.requirementsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://energycode.pnl.gov/ns/ComCheckBuildingSchema")]
public partial class buildingControl {
    
    private string codeField;
    
    private string complianceModeField;
    
    private string versionField;
    
    /// <remarks/>
    public string code {
        get {
            return this.codeField;
        }
        set {
            this.codeField = value;
        }
    }
    
    /// <remarks/>
    public string complianceMode {
        get {
            return this.complianceModeField;
        }
        set {
            this.complianceModeField = value;
        }
    }
    
    /// <remarks/>
    public string version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://energycode.pnl.gov/ns/ComCheckBuildingSchema")]
public partial class buildingLocation {
    
    private string stateField;
    
    private string cityField;
    
    /// <remarks/>
    public string state {
        get {
            return this.stateField;
        }
        set {
            this.stateField = value;
        }
    }
    
    /// <remarks/>
    public string city {
        get {
            return this.cityField;
        }
        set {
            this.cityField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://energycode.pnl.gov/ns/ComCheckBuildingSchema")]
public partial class buildingProject {
    
    private string projectTitleField;
    
    private string projectAddressField;
    
    private string projectCityField;
    
    private string projectStateField;
    
    private string projectZipCodeField;
    
    private string developerCompanyField;
    
    private string developerAddressField;
    
    private string developerCityField;
    
    private string developerStateField;
    
    private string developerZipCodeField;
    
    private bool projectCompleteField;
    
    /// <remarks/>
    public string projectTitle {
        get {
            return this.projectTitleField;
        }
        set {
            this.projectTitleField = value;
        }
    }
    
    /// <remarks/>
    public string projectAddress {
        get {
            return this.projectAddressField;
        }
        set {
            this.projectAddressField = value;
        }
    }
    
    /// <remarks/>
    public string projectCity {
        get {
            return this.projectCityField;
        }
        set {
            this.projectCityField = value;
        }
    }
    
    /// <remarks/>
    public string projectState {
        get {
            return this.projectStateField;
        }
        set {
            this.projectStateField = value;
        }
    }
    
    /// <remarks/>
    public string projectZipCode {
        get {
            return this.projectZipCodeField;
        }
        set {
            this.projectZipCodeField = value;
        }
    }
    
    /// <remarks/>
    public string developerCompany {
        get {
            return this.developerCompanyField;
        }
        set {
            this.developerCompanyField = value;
        }
    }
    
    /// <remarks/>
    public string developerAddress {
        get {
            return this.developerAddressField;
        }
        set {
            this.developerAddressField = value;
        }
    }
    
    /// <remarks/>
    public string developerCity {
        get {
            return this.developerCityField;
        }
        set {
            this.developerCityField = value;
        }
    }
    
    /// <remarks/>
    public string developerState {
        get {
            return this.developerStateField;
        }
        set {
            this.developerStateField = value;
        }
    }
    
    /// <remarks/>
    public string developerZipCode {
        get {
            return this.developerZipCodeField;
        }
        set {
            this.developerZipCodeField = value;
        }
    }
    
    /// <remarks/>
    public bool projectComplete {
        get {
            return this.projectCompleteField;
        }
        set {
            this.projectCompleteField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://energycode.pnl.gov/ns/ComCheckBuildingSchema")]
public partial class buildingEnvelope {
    
    private decimal postAltWindowWallPctField;
    
    private decimal postAltSkylightRoofPctField;
    
    private decimal altPctGlazingAreaReplacedField;
    
    private decimal altPctSkylightAreaReplacedField;
    
    private bool useOrientDetailsField;
    
    private bool useVltDetailsField;
    
    private bool useCoolRoofPerformanceDetailsField;
    
    private string airBarrierComplianceTypeField;
    
    private bool applyWindowPctAllowanceForDaylightingField;
    
    private bool applySkylightPctAllowanceForDaylightingField;
    
    /// <remarks/>
    public decimal postAltWindowWallPct {
        get {
            return this.postAltWindowWallPctField;
        }
        set {
            this.postAltWindowWallPctField = value;
        }
    }
    
    /// <remarks/>
    public decimal postAltSkylightRoofPct {
        get {
            return this.postAltSkylightRoofPctField;
        }
        set {
            this.postAltSkylightRoofPctField = value;
        }
    }
    
    /// <remarks/>
    public decimal altPctGlazingAreaReplaced {
        get {
            return this.altPctGlazingAreaReplacedField;
        }
        set {
            this.altPctGlazingAreaReplacedField = value;
        }
    }
    
    /// <remarks/>
    public decimal altPctSkylightAreaReplaced {
        get {
            return this.altPctSkylightAreaReplacedField;
        }
        set {
            this.altPctSkylightAreaReplacedField = value;
        }
    }
    
    /// <remarks/>
    public bool useOrientDetails {
        get {
            return this.useOrientDetailsField;
        }
        set {
            this.useOrientDetailsField = value;
        }
    }
    
    /// <remarks/>
    public bool useVltDetails {
        get {
            return this.useVltDetailsField;
        }
        set {
            this.useVltDetailsField = value;
        }
    }
    
    /// <remarks/>
    public bool useCoolRoofPerformanceDetails {
        get {
            return this.useCoolRoofPerformanceDetailsField;
        }
        set {
            this.useCoolRoofPerformanceDetailsField = value;
        }
    }
    
    /// <remarks/>
    public string airBarrierComplianceType {
        get {
            return this.airBarrierComplianceTypeField;
        }
        set {
            this.airBarrierComplianceTypeField = value;
        }
    }
    
    /// <remarks/>
    public bool applyWindowPctAllowanceForDaylighting {
        get {
            return this.applyWindowPctAllowanceForDaylightingField;
        }
        set {
            this.applyWindowPctAllowanceForDaylightingField = value;
        }
    }
    
    /// <remarks/>
    public bool applySkylightPctAllowanceForDaylighting {
        get {
            return this.applySkylightPctAllowanceForDaylightingField;
        }
        set {
            this.applySkylightPctAllowanceForDaylightingField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://energycode.pnl.gov/ns/ComCheckBuildingSchema")]
public partial class buildingLighting {
    
    private byte exteriorLightingZoneField;
    
    private string exteriorLightingZoneTypeField;
    
    private buildingLightingWholeBldgUses wholeBldgUsesField;
    
    private buildingLightingActivityUses activityUsesField;
    
    private buildingLightingExteriorUses exteriorUsesField;
    
    /// <remarks/>
    public byte exteriorLightingZone {
        get {
            return this.exteriorLightingZoneField;
        }
        set {
            this.exteriorLightingZoneField = value;
        }
    }
    
    /// <remarks/>
    public string exteriorLightingZoneType {
        get {
            return this.exteriorLightingZoneTypeField;
        }
        set {
            this.exteriorLightingZoneTypeField = value;
        }
    }
    
    /// <remarks/>
    public buildingLightingWholeBldgUses wholeBldgUses {
        get {
            return this.wholeBldgUsesField;
        }
        set {
            this.wholeBldgUsesField = value;
        }
    }
    
    /// <remarks/>
    public buildingLightingActivityUses activityUses {
        get {
            return this.activityUsesField;
        }
        set {
            this.activityUsesField = value;
        }
    }
    
    /// <remarks/>
    public buildingLightingExteriorUses exteriorUses {
        get {
            return this.exteriorUsesField;
        }
        set {
            this.exteriorUsesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://energycode.pnl.gov/ns/ComCheckBuildingSchema")]
public partial class buildingLightingWholeBldgUses {
    
    private buildingLightingWholeBldgUsesWholeBldgUse wholeBldgUseField;
    
    /// <remarks/>
    public buildingLightingWholeBldgUsesWholeBldgUse wholeBldgUse {
        get {
            return this.wholeBldgUseField;
        }
        set {
            this.wholeBldgUseField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://energycode.pnl.gov/ns/ComCheckBuildingSchema")]
public partial class buildingLightingWholeBldgUsesWholeBldgUse {
    
    private string wholeBldgTypeField;
    
    private uint keyField;
    
    private decimal powerDensityField;
    
    private decimal internalLoadField;
    
    private byte ceilingHeightField;
    
    private byte listPositionField;
    
    private string constructionTypeField;
    
    private ushort floorAreaField;
    
    private buildingLightingWholeBldgUsesWholeBldgUseInteriorLightingSpace interiorLightingSpaceField;
    
    /// <remarks/>
    public string wholeBldgType {
        get {
            return this.wholeBldgTypeField;
        }
        set {
            this.wholeBldgTypeField = value;
        }
    }
    
    /// <remarks/>
    public uint key {
        get {
            return this.keyField;
        }
        set {
            this.keyField = value;
        }
    }
    
    /// <remarks/>
    public decimal powerDensity {
        get {
            return this.powerDensityField;
        }
        set {
            this.powerDensityField = value;
        }
    }
    
    /// <remarks/>
    public decimal internalLoad {
        get {
            return this.internalLoadField;
        }
        set {
            this.internalLoadField = value;
        }
    }
    
    /// <remarks/>
    public byte ceilingHeight {
        get {
            return this.ceilingHeightField;
        }
        set {
            this.ceilingHeightField = value;
        }
    }
    
    /// <remarks/>
    public byte listPosition {
        get {
            return this.listPositionField;
        }
        set {
            this.listPositionField = value;
        }
    }
    
    /// <remarks/>
    public string constructionType {
        get {
            return this.constructionTypeField;
        }
        set {
            this.constructionTypeField = value;
        }
    }
    
    /// <remarks/>
    public ushort floorArea {
        get {
            return this.floorAreaField;
        }
        set {
            this.floorAreaField = value;
        }
    }
    
    /// <remarks/>
    public buildingLightingWholeBldgUsesWholeBldgUseInteriorLightingSpace interiorLightingSpace {
        get {
            return this.interiorLightingSpaceField;
        }
        set {
            this.interiorLightingSpaceField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://energycode.pnl.gov/ns/ComCheckBuildingSchema")]
public partial class buildingLightingWholeBldgUsesWholeBldgUseInteriorLightingSpace {
    
    private string descriptionField;
    
    private string altExemptTypeField;
    
    private byte preAltNumberFixturesField;
    
    private byte numFixturesAlteredOrAddedField;
    
    private decimal preAltTotalWattageField;
    
    private decimal postAltTotalWattageField;
    
    private string allowanceTypeField;
    
    private byte allowanceFloorAreaField;
    
    private byte rcrPerimeterField;
    
    private byte rcrFloorToWorkplaneHeightField;
    
    private byte rcrWorkplaneToLuminaireHeightField;
    
    private buildingLightingWholeBldgUsesWholeBldgUseInteriorLightingSpaceFixture[] fixturesField;
    
    /// <remarks/>
    public string description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    public string altExemptType {
        get {
            return this.altExemptTypeField;
        }
        set {
            this.altExemptTypeField = value;
        }
    }
    
    /// <remarks/>
    public byte preAltNumberFixtures {
        get {
            return this.preAltNumberFixturesField;
        }
        set {
            this.preAltNumberFixturesField = value;
        }
    }
    
    /// <remarks/>
    public byte numFixturesAlteredOrAdded {
        get {
            return this.numFixturesAlteredOrAddedField;
        }
        set {
            this.numFixturesAlteredOrAddedField = value;
        }
    }
    
    /// <remarks/>
    public decimal preAltTotalWattage {
        get {
            return this.preAltTotalWattageField;
        }
        set {
            this.preAltTotalWattageField = value;
        }
    }
    
    /// <remarks/>
    public decimal postAltTotalWattage {
        get {
            return this.postAltTotalWattageField;
        }
        set {
            this.postAltTotalWattageField = value;
        }
    }
    
    /// <remarks/>
    public string allowanceType {
        get {
            return this.allowanceTypeField;
        }
        set {
            this.allowanceTypeField = value;
        }
    }
    
    /// <remarks/>
    public byte allowanceFloorArea {
        get {
            return this.allowanceFloorAreaField;
        }
        set {
            this.allowanceFloorAreaField = value;
        }
    }
    
    /// <remarks/>
    public byte rcrPerimeter {
        get {
            return this.rcrPerimeterField;
        }
        set {
            this.rcrPerimeterField = value;
        }
    }
    
    /// <remarks/>
    public byte rcrFloorToWorkplaneHeight {
        get {
            return this.rcrFloorToWorkplaneHeightField;
        }
        set {
            this.rcrFloorToWorkplaneHeightField = value;
        }
    }
    
    /// <remarks/>
    public byte rcrWorkplaneToLuminaireHeight {
        get {
            return this.rcrWorkplaneToLuminaireHeightField;
        }
        set {
            this.rcrWorkplaneToLuminaireHeightField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("fixture", IsNullable=false)]
    public buildingLightingWholeBldgUsesWholeBldgUseInteriorLightingSpaceFixture[] fixtures {
        get {
            return this.fixturesField;
        }
        set {
            this.fixturesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://energycode.pnl.gov/ns/ComCheckBuildingSchema")]
public partial class buildingLightingWholeBldgUsesWholeBldgUseInteriorLightingSpaceFixture {
    
    private byte listPositionField;
    
    private decimal lampWattageField;
    
    private string lightingTypeField;
    
    private string typeOfFixtureField;
    
    private string fixtureTypeField;
    
    private string lampTypeField;
    
    private byte numberOfLampsField;
    
    private decimal fixtureWattageField;
    
    private byte quantityField;
    
    /// <remarks/>
    public byte listPosition {
        get {
            return this.listPositionField;
        }
        set {
            this.listPositionField = value;
        }
    }
    
    /// <remarks/>
    public decimal lampWattage {
        get {
            return this.lampWattageField;
        }
        set {
            this.lampWattageField = value;
        }
    }
    
    /// <remarks/>
    public string lightingType {
        get {
            return this.lightingTypeField;
        }
        set {
            this.lightingTypeField = value;
        }
    }
    
    /// <remarks/>
    public string typeOfFixture {
        get {
            return this.typeOfFixtureField;
        }
        set {
            this.typeOfFixtureField = value;
        }
    }
    
    /// <remarks/>
    public string fixtureType {
        get {
            return this.fixtureTypeField;
        }
        set {
            this.fixtureTypeField = value;
        }
    }
    
    /// <remarks/>
    public string lampType {
        get {
            return this.lampTypeField;
        }
        set {
            this.lampTypeField = value;
        }
    }
    
    /// <remarks/>
    public byte numberOfLamps {
        get {
            return this.numberOfLampsField;
        }
        set {
            this.numberOfLampsField = value;
        }
    }
    
    /// <remarks/>
    public decimal fixtureWattage {
        get {
            return this.fixtureWattageField;
        }
        set {
            this.fixtureWattageField = value;
        }
    }
    
    /// <remarks/>
    public byte quantity {
        get {
            return this.quantityField;
        }
        set {
            this.quantityField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://energycode.pnl.gov/ns/ComCheckBuildingSchema")]
public partial class buildingLightingActivityUses {
    
    private buildingLightingActivityUsesActivityUse activityUseField;
    
    /// <remarks/>
    public buildingLightingActivityUsesActivityUse activityUse {
        get {
            return this.activityUseField;
        }
        set {
            this.activityUseField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://energycode.pnl.gov/ns/ComCheckBuildingSchema")]
public partial class buildingLightingActivityUsesActivityUse {
    
    private uint keyField;
    
    private string activityTypeField;
    
    private byte powerDensityField;
    
    private byte ceilingHeightField;
    
    private byte internalLoadField;
    
    private byte listPositionField;
    
    private string constructionTypeField;
    
    private byte floorAreaField;
    
    /// <remarks/>
    public uint key {
        get {
            return this.keyField;
        }
        set {
            this.keyField = value;
        }
    }
    
    /// <remarks/>
    public string activityType {
        get {
            return this.activityTypeField;
        }
        set {
            this.activityTypeField = value;
        }
    }
    
    /// <remarks/>
    public byte powerDensity {
        get {
            return this.powerDensityField;
        }
        set {
            this.powerDensityField = value;
        }
    }
    
    /// <remarks/>
    public byte ceilingHeight {
        get {
            return this.ceilingHeightField;
        }
        set {
            this.ceilingHeightField = value;
        }
    }
    
    /// <remarks/>
    public byte internalLoad {
        get {
            return this.internalLoadField;
        }
        set {
            this.internalLoadField = value;
        }
    }
    
    /// <remarks/>
    public byte listPosition {
        get {
            return this.listPositionField;
        }
        set {
            this.listPositionField = value;
        }
    }
    
    /// <remarks/>
    public string constructionType {
        get {
            return this.constructionTypeField;
        }
        set {
            this.constructionTypeField = value;
        }
    }
    
    /// <remarks/>
    public byte floorArea {
        get {
            return this.floorAreaField;
        }
        set {
            this.floorAreaField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://energycode.pnl.gov/ns/ComCheckBuildingSchema")]
public partial class buildingLightingExteriorUses {
    
    private buildingLightingExteriorUsesExteriorUse exteriorUseField;
    
    /// <remarks/>
    public buildingLightingExteriorUsesExteriorUse exteriorUse {
        get {
            return this.exteriorUseField;
        }
        set {
            this.exteriorUseField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://energycode.pnl.gov/ns/ComCheckBuildingSchema")]
public partial class buildingLightingExteriorUsesExteriorUse {
    
    private uint keyField;
    
    private string exteriorTypeField;
    
    private byte powerDensityField;
    
    private byte useQuantityField;
    
    private bool isTradableField;
    
    /// <remarks/>
    public uint key {
        get {
            return this.keyField;
        }
        set {
            this.keyField = value;
        }
    }
    
    /// <remarks/>
    public string exteriorType {
        get {
            return this.exteriorTypeField;
        }
        set {
            this.exteriorTypeField = value;
        }
    }
    
    /// <remarks/>
    public byte powerDensity {
        get {
            return this.powerDensityField;
        }
        set {
            this.powerDensityField = value;
        }
    }
    
    /// <remarks/>
    public byte useQuantity {
        get {
            return this.useQuantityField;
        }
        set {
            this.useQuantityField = value;
        }
    }
    
    /// <remarks/>
    public bool isTradable {
        get {
            return this.isTradableField;
        }
        set {
            this.isTradableField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://energycode.pnl.gov/ns/ComCheckBuildingSchema")]
public partial class buildingHvac {
    
    private buildingHvacHvacSystems hvacSystemsField;
    
    private buildingHvacFanSystems fanSystemsField;
    
    /// <remarks/>
    public buildingHvacHvacSystems hvacSystems {
        get {
            return this.hvacSystemsField;
        }
        set {
            this.hvacSystemsField = value;
        }
    }
    
    /// <remarks/>
    public buildingHvacFanSystems fanSystems {
        get {
            return this.fanSystemsField;
        }
        set {
            this.fanSystemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://energycode.pnl.gov/ns/ComCheckBuildingSchema")]
public partial class buildingHvacHvacSystems {
    
    private buildingHvacHvacSystemsHvacSystem hvacSystemField;
    
    /// <remarks/>
    public buildingHvacHvacSystemsHvacSystem hvacSystem {
        get {
            return this.hvacSystemField;
        }
        set {
            this.hvacSystemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://energycode.pnl.gov/ns/ComCheckBuildingSchema")]
public partial class buildingHvacHvacSystemsHvacSystem {
    
    private string descriptionField;
    
    private byte quantityField;
    
    private string altExemptTypeField;
    
    private byte listPositionField;
    
    private string descriptionHeatEquipField;
    
    private string descriptionCoolEquipField;
    
    private string heatingEquipmentField;
    
    private string coolingEquipmentField;
    
    private string heatPumpField;
    
    private byte quantityHeatEquipField;
    
    private byte quantityCoolEquipField;
    
    private string zoneField;
    
    private bool perimeterSystemField;
    
    private bool isHeatingSysWeatherizedField;
    
    private decimal heatingEquipCapacityField;
    
    private decimal propHeatingEquipEfficiencyField;
    
    private decimal coolingEquipCapacityField;
    
    private decimal propCoolingEquipEfficiencyField;
    
    private string fuelField;
    
    private string distributionField;
    
    private bool varAirBoxField;
    
    private bool fanPoweredVavField;
    
    private bool varAirVolMixingBoxField;
    
    private bool constVolMixingBoxField;
    
    private bool reheatRecoolCoilField;
    
    private bool electricReheatField;
    
    private bool hydronicReheatField;
    
    private bool steamReheatField;
    
    private string condenserField;
    
    private string economizerField;
    
    private string economizerExceptionField;
    
    private string fanControlField;
    
    private decimal supplyFanHpField;
    
    private decimal supplyStaticPressureField;
    
    private decimal returnFanHpField;
    
    private uint fanSystemKeyField;
    
    private decimal totalFanHpField;
    
    private buildingHvacHvacSystemsHvacSystemRequirementAnswer[] requirementsField;
    
    /// <remarks/>
    public string description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    public byte quantity {
        get {
            return this.quantityField;
        }
        set {
            this.quantityField = value;
        }
    }
    
    /// <remarks/>
    public string altExemptType {
        get {
            return this.altExemptTypeField;
        }
        set {
            this.altExemptTypeField = value;
        }
    }
    
    /// <remarks/>
    public byte listPosition {
        get {
            return this.listPositionField;
        }
        set {
            this.listPositionField = value;
        }
    }
    
    /// <remarks/>
    public string descriptionHeatEquip {
        get {
            return this.descriptionHeatEquipField;
        }
        set {
            this.descriptionHeatEquipField = value;
        }
    }
    
    /// <remarks/>
    public string descriptionCoolEquip {
        get {
            return this.descriptionCoolEquipField;
        }
        set {
            this.descriptionCoolEquipField = value;
        }
    }
    
    /// <remarks/>
    public string heatingEquipment {
        get {
            return this.heatingEquipmentField;
        }
        set {
            this.heatingEquipmentField = value;
        }
    }
    
    /// <remarks/>
    public string coolingEquipment {
        get {
            return this.coolingEquipmentField;
        }
        set {
            this.coolingEquipmentField = value;
        }
    }
    
    /// <remarks/>
    public string heatPump {
        get {
            return this.heatPumpField;
        }
        set {
            this.heatPumpField = value;
        }
    }
    
    /// <remarks/>
    public byte quantityHeatEquip {
        get {
            return this.quantityHeatEquipField;
        }
        set {
            this.quantityHeatEquipField = value;
        }
    }
    
    /// <remarks/>
    public byte quantityCoolEquip {
        get {
            return this.quantityCoolEquipField;
        }
        set {
            this.quantityCoolEquipField = value;
        }
    }
    
    /// <remarks/>
    public string zone {
        get {
            return this.zoneField;
        }
        set {
            this.zoneField = value;
        }
    }
    
    /// <remarks/>
    public bool perimeterSystem {
        get {
            return this.perimeterSystemField;
        }
        set {
            this.perimeterSystemField = value;
        }
    }
    
    /// <remarks/>
    public bool isHeatingSysWeatherized {
        get {
            return this.isHeatingSysWeatherizedField;
        }
        set {
            this.isHeatingSysWeatherizedField = value;
        }
    }
    
    /// <remarks/>
    public decimal heatingEquipCapacity {
        get {
            return this.heatingEquipCapacityField;
        }
        set {
            this.heatingEquipCapacityField = value;
        }
    }
    
    /// <remarks/>
    public decimal propHeatingEquipEfficiency {
        get {
            return this.propHeatingEquipEfficiencyField;
        }
        set {
            this.propHeatingEquipEfficiencyField = value;
        }
    }
    
    /// <remarks/>
    public decimal coolingEquipCapacity {
        get {
            return this.coolingEquipCapacityField;
        }
        set {
            this.coolingEquipCapacityField = value;
        }
    }
    
    /// <remarks/>
    public decimal propCoolingEquipEfficiency {
        get {
            return this.propCoolingEquipEfficiencyField;
        }
        set {
            this.propCoolingEquipEfficiencyField = value;
        }
    }
    
    /// <remarks/>
    public string fuel {
        get {
            return this.fuelField;
        }
        set {
            this.fuelField = value;
        }
    }
    
    /// <remarks/>
    public string distribution {
        get {
            return this.distributionField;
        }
        set {
            this.distributionField = value;
        }
    }
    
    /// <remarks/>
    public bool varAirBox {
        get {
            return this.varAirBoxField;
        }
        set {
            this.varAirBoxField = value;
        }
    }
    
    /// <remarks/>
    public bool fanPoweredVav {
        get {
            return this.fanPoweredVavField;
        }
        set {
            this.fanPoweredVavField = value;
        }
    }
    
    /// <remarks/>
    public bool varAirVolMixingBox {
        get {
            return this.varAirVolMixingBoxField;
        }
        set {
            this.varAirVolMixingBoxField = value;
        }
    }
    
    /// <remarks/>
    public bool constVolMixingBox {
        get {
            return this.constVolMixingBoxField;
        }
        set {
            this.constVolMixingBoxField = value;
        }
    }
    
    /// <remarks/>
    public bool reheatRecoolCoil {
        get {
            return this.reheatRecoolCoilField;
        }
        set {
            this.reheatRecoolCoilField = value;
        }
    }
    
    /// <remarks/>
    public bool electricReheat {
        get {
            return this.electricReheatField;
        }
        set {
            this.electricReheatField = value;
        }
    }
    
    /// <remarks/>
    public bool hydronicReheat {
        get {
            return this.hydronicReheatField;
        }
        set {
            this.hydronicReheatField = value;
        }
    }
    
    /// <remarks/>
    public bool steamReheat {
        get {
            return this.steamReheatField;
        }
        set {
            this.steamReheatField = value;
        }
    }
    
    /// <remarks/>
    public string condenser {
        get {
            return this.condenserField;
        }
        set {
            this.condenserField = value;
        }
    }
    
    /// <remarks/>
    public string economizer {
        get {
            return this.economizerField;
        }
        set {
            this.economizerField = value;
        }
    }
    
    /// <remarks/>
    public string economizerException {
        get {
            return this.economizerExceptionField;
        }
        set {
            this.economizerExceptionField = value;
        }
    }
    
    /// <remarks/>
    public string fanControl {
        get {
            return this.fanControlField;
        }
        set {
            this.fanControlField = value;
        }
    }
    
    /// <remarks/>
    public decimal supplyFanHp {
        get {
            return this.supplyFanHpField;
        }
        set {
            this.supplyFanHpField = value;
        }
    }
    
    /// <remarks/>
    public decimal supplyStaticPressure {
        get {
            return this.supplyStaticPressureField;
        }
        set {
            this.supplyStaticPressureField = value;
        }
    }
    
    /// <remarks/>
    public decimal returnFanHp {
        get {
            return this.returnFanHpField;
        }
        set {
            this.returnFanHpField = value;
        }
    }
    
    /// <remarks/>
    public uint fanSystemKey {
        get {
            return this.fanSystemKeyField;
        }
        set {
            this.fanSystemKeyField = value;
        }
    }
    
    /// <remarks/>
    public decimal totalFanHp {
        get {
            return this.totalFanHpField;
        }
        set {
            this.totalFanHpField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("requirementAnswer", IsNullable=false)]
    public buildingHvacHvacSystemsHvacSystemRequirementAnswer[] requirements {
        get {
            return this.requirementsField;
        }
        set {
            this.requirementsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://energycode.pnl.gov/ns/ComCheckBuildingSchema")]
public partial class buildingHvacHvacSystemsHvacSystemRequirementAnswer {
    
    private string requirementField;
    
    private string categoryField;
    
    private string exceptionNameField;
    
    private string statusField;
    
    /// <remarks/>
    public string requirement {
        get {
            return this.requirementField;
        }
        set {
            this.requirementField = value;
        }
    }
    
    /// <remarks/>
    public string category {
        get {
            return this.categoryField;
        }
        set {
            this.categoryField = value;
        }
    }
    
    /// <remarks/>
    public string exceptionName {
        get {
            return this.exceptionNameField;
        }
        set {
            this.exceptionNameField = value;
        }
    }
    
    /// <remarks/>
    public string status {
        get {
            return this.statusField;
        }
        set {
            this.statusField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://energycode.pnl.gov/ns/ComCheckBuildingSchema")]
public partial class buildingHvacFanSystems {
    
    private buildingHvacFanSystemsFanSystem fanSystemField;
    
    /// <remarks/>
    public buildingHvacFanSystemsFanSystem fanSystem {
        get {
            return this.fanSystemField;
        }
        set {
            this.fanSystemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://energycode.pnl.gov/ns/ComCheckBuildingSchema")]
public partial class buildingHvacFanSystemsFanSystem {
    
    private uint keyField;
    
    private string descriptionField;
    
    private byte listPositionField;
    
    private bool servesAllowanceAreaWithFlowControlField;
    
    private bool hasPressureDropCreditsField;
    
    private string complyMethodField;
    
    private buildingHvacFanSystemsFanSystemFans fansField;
    
    /// <remarks/>
    public uint key {
        get {
            return this.keyField;
        }
        set {
            this.keyField = value;
        }
    }
    
    /// <remarks/>
    public string description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    public byte listPosition {
        get {
            return this.listPositionField;
        }
        set {
            this.listPositionField = value;
        }
    }
    
    /// <remarks/>
    public bool servesAllowanceAreaWithFlowControl {
        get {
            return this.servesAllowanceAreaWithFlowControlField;
        }
        set {
            this.servesAllowanceAreaWithFlowControlField = value;
        }
    }
    
    /// <remarks/>
    public bool hasPressureDropCredits {
        get {
            return this.hasPressureDropCreditsField;
        }
        set {
            this.hasPressureDropCreditsField = value;
        }
    }
    
    /// <remarks/>
    public string complyMethod {
        get {
            return this.complyMethodField;
        }
        set {
            this.complyMethodField = value;
        }
    }
    
    /// <remarks/>
    public buildingHvacFanSystemsFanSystemFans fans {
        get {
            return this.fansField;
        }
        set {
            this.fansField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://energycode.pnl.gov/ns/ComCheckBuildingSchema")]
public partial class buildingHvacFanSystemsFanSystemFans {
    
    private buildingHvacFanSystemsFanSystemFansFan fanField;
    
    /// <remarks/>
    public buildingHvacFanSystemsFanSystemFansFan fan {
        get {
            return this.fanField;
        }
        set {
            this.fanField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://energycode.pnl.gov/ns/ComCheckBuildingSchema")]
public partial class buildingHvacFanSystemsFanSystemFansFan {
    
    private string descriptionField;
    
    private byte listPositionField;
    
    private decimal nameplateHpField;
    
    private decimal brakeHpField;
    
    private decimal designBrakeHpField;
    
    private decimal volumeField;
    
    private decimal fanEfficiencyField;
    
    private decimal totalFanEfficiencyField;
    
    private decimal fanDesignEfficiencyField;
    
    private string fanEfficiencyExceptionTypeField;
    
    private string fanTypeField;
    
    private string fanVolumeTypeField;
    
    /// <remarks/>
    public string description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    public byte listPosition {
        get {
            return this.listPositionField;
        }
        set {
            this.listPositionField = value;
        }
    }
    
    /// <remarks/>
    public decimal nameplateHp {
        get {
            return this.nameplateHpField;
        }
        set {
            this.nameplateHpField = value;
        }
    }
    
    /// <remarks/>
    public decimal brakeHp {
        get {
            return this.brakeHpField;
        }
        set {
            this.brakeHpField = value;
        }
    }
    
    /// <remarks/>
    public decimal designBrakeHp {
        get {
            return this.designBrakeHpField;
        }
        set {
            this.designBrakeHpField = value;
        }
    }
    
    /// <remarks/>
    public decimal volume {
        get {
            return this.volumeField;
        }
        set {
            this.volumeField = value;
        }
    }
    
    /// <remarks/>
    public decimal fanEfficiency {
        get {
            return this.fanEfficiencyField;
        }
        set {
            this.fanEfficiencyField = value;
        }
    }
    
    /// <remarks/>
    public decimal totalFanEfficiency {
        get {
            return this.totalFanEfficiencyField;
        }
        set {
            this.totalFanEfficiencyField = value;
        }
    }
    
    /// <remarks/>
    public decimal fanDesignEfficiency {
        get {
            return this.fanDesignEfficiencyField;
        }
        set {
            this.fanDesignEfficiencyField = value;
        }
    }
    
    /// <remarks/>
    public string fanEfficiencyExceptionType {
        get {
            return this.fanEfficiencyExceptionTypeField;
        }
        set {
            this.fanEfficiencyExceptionTypeField = value;
        }
    }
    
    /// <remarks/>
    public string fanType {
        get {
            return this.fanTypeField;
        }
        set {
            this.fanTypeField = value;
        }
    }
    
    /// <remarks/>
    public string fanVolumeType {
        get {
            return this.fanVolumeTypeField;
        }
        set {
            this.fanVolumeTypeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://energycode.pnl.gov/ns/ComCheckBuildingSchema")]
public partial class buildingRequirementAnswer {
    
    private string requirementField;
    
    private string categoryField;
    
    private string exceptionNameField;
    
    private string statusField;
    
    /// <remarks/>
    public string requirement {
        get {
            return this.requirementField;
        }
        set {
            this.requirementField = value;
        }
    }
    
    /// <remarks/>
    public string category {
        get {
            return this.categoryField;
        }
        set {
            this.categoryField = value;
        }
    }
    
    /// <remarks/>
    public string exceptionName {
        get {
            return this.exceptionNameField;
        }
        set {
            this.exceptionNameField = value;
        }
    }
    
    /// <remarks/>
    public string status {
        get {
            return this.statusField;
        }
        set {
            this.statusField = value;
        }
    }
}
